```{r}
#Import libraries and install packages
library(openair)
library(lubridate)
```

```{r}
#Import Data
pr_winter2020 <- read.csv2("https://raw.githubusercontent.com/lourdesvera/Community_Air_Montoring/master/Wind_Analyses/Wind%20Pollution%202%20yrs.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
pr_winter2020
```

```{r}
#rename column names
colnames(pr_winter2020) = c("date", "PM2.5", "ws", "wd")
```

```{r}
#convert all variables to "numeric" since they are in "character"
pr_winter2020$PM2.5 <- as.numeric(as.character(pr_winter2020$PM2.5))
pr_winter2020$date <- as.Date(as.character(pr_winter2020$date))
pr_winter2020$ws <- as.numeric(as.character(pr_winter2020$ws))
pr_winter2020$wd <- as.numeric(as.character(pr_winter2020$wd))
```

```{r}
#date selection
pr_winter2020 <- selectByDate(pr_winter2020, start = "2020-12-21", end = "2021-03-19")
```

```{r}
summary(pr_winter2020)
```

```{r}
str(pr_winter2020)
```

```{r}
View(pr_winter2020)
```

```{r}
#get classes of all columns
sapply(pr_winter2020, class)
```

```{r}
summary(pr_winter2020)
```

```{r}
#Prep for pollution rose
ad_pr <- pr_winter2020[,c("ws", "wd", "PM2.5")]
```

```{r}
#pollution rose
pollutionRose(ad_pr, ws = "ws", wd = "wd", pollutant = "PM2.5", key.footer = "Winter 2020 PM2.5 Plot in Armourdale, KS (ug/m^3)", key.position = "right", breaks = c(0,15,30,45,60,100), grid.line = 5, key = list(labels = c("0-15", "16-30", "31-45", "46-60", "60+")))
```
